---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 3scale-status-checker
  namespace: 3scale
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 3scale-status-checker
subjects:
- kind: ServiceAccount
  name: 3scale-status-checker
  namespace: 3scale
