---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: 3scale-patcher
  namespace: 3scale
  annotations:
    argocd.argoproj.io/sync-wave: "3"
rules:
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - patch
  - update
