---
apiVersion: v1
kind: Secret
metadata:
  name: cp-bearer
  namespace: 3scale
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
stringData:
  policy.lua: |
    local _M = require('apicast.policy').new('Remove Bearer', '0.1')
    
    function _M:rewrite()
      local auth_header = ngx.var.http_authorization
      if auth_header then
        local token = auth_header:match("^Bearer%s+(.+)")
        if token then
          ngx.req.set_header("Authorization", token)
        end
      end
    end
    
    return _M
