apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-configs
spec:
  generators:
  - list:
      elements:
      # MachineSet scaler - runs first with sync-wave -5
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: machineset-scaler
          path: components/cluster-configs/machineset-scaler/overlays/default
      
      # Existing configs
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: user-workload-monitoring
          path: components/cluster-configs/user-workload-monitoring/overlays/default
